module.exports = {
  globals: {
    'ts-jest': {
      tsconfig: 'tsconfig.spec.json',
    },
  },
  preset: 'ts-jest',
  testEnvironment: 'node',
  roots: ['<rootDir>/src/', '<rootDir>/test/'],
  // this is a workaround that jest does not create a jest_0/ folder in the project root dir!
  cacheDirectory: '/tmp/jest-cache',
  collectCoverageFrom: [
    'src/**/*.ts',
    // 'src/graphql/apollo/client/apollo-client-factory.ts',
    // 'src/graphql/graphql-handler.ts',
    // 'src/graphql/graphql-server.ts',
    // 'src/graphql/type-graphql/schema-common-mixins.ts',
    // 'src/graphql/type-graphql/schema-resolvers/about/graphql-resolver.ts',
    // 'src/graphql/type-graphql/schema-resolvers/location/decorators.ts',
    // 'src/graphql/type-graphql/schema-resolvers/location/graphql-resolver.ts',
    // 'src/shared/aws.ts',
    // 'src/shared/steps.ts',
    // 'src/shared/mapper.ts',
    // 'src/utils/graphql/apollo/server/lambda/apollo-server-lambda-handler-factory.ts',
    // 'src/utils/graphql/apollo/server/lambda/graphql-lambda-handler-factory.ts',
    // 'src/utils/graphql/apollo/server/plugins/basic-apollo-server-plugin-factory.ts',
    // 'src/utils/graphql/apollo/server/options/graphql-api-options.ts',
    // 'src/utils/graphql/apollo/server/graphql-server-application.ts',
  ],
  coverageDirectory: './coverage/',
  coverageReporters: ['json-summary', 'html', 'lcov', 'lcovonly', 'text'],
  coverageThreshold: {
    global: {
      statements: 100,
      branches: 100,
      functions: 100,
      lines: 100,
    },
  },
  testMatch: [
    '<rootDir>/test/**/*',
    // '<rootDir>/test/graphql/apollo/client/apollo-client-factory.test.ts',
    // '<rootDir>/test/graphql/apollo/client/clients.test.ts',
    // '<rootDir>/test/graphql/graphql-handler.test.ts',
    // '<rootDir>/test/graphql/graphql-server.test.ts',
    // '<rootDir>/test/graphql/type-graphql/schema-common-mixins.test.ts',
    // '<rootDir>/test/graphql/type-graphql/schema-resolvers/about/graphql-resolver.test.ts',
    // '<rootDir>/test/graphql/type-graphql/schema-resolvers/location/decorators.test.ts',
    // '<rootDir>/test/graphql/type-graphql/schema-resolvers/location/graphql-resolver.test.ts',
    // '<rootDir>/test/shared/aws.test.ts',
    // '<rootDir>/test/shared/steps.test.ts',
    // '<rootDir>/test/shared/mapper.test.ts',
    // '<rootDir>/test/utils/graphql/apollo/server/lambda/apollo-server-lambda-handler-factory.test.ts',
    // '<rootDir>/test/utils/graphql/apollo/server/lambda/graphql-lambda-handler-factory.test.ts',
    // '<rootDir>/test/utils/graphql/apollo/server/plugins/basic-apollo-server-plugin-factory.test.ts',
    // '<rootDir>/test/utils/graphql/apollo/server/options/graphql-api-options.test.ts',
    // '<rootDir>/test/utils/graphql/apollo/server/graphql-server-application.test.ts',
  ],
  testPathIgnorePatterns: ['<rootDir>/test/.*/*.test-data.ts', '<rootDir>/test/graphql/type-graphql/schema-resolvers/about/about.json'],
  verbose: true,
};
